cicd: checks added

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,8 +4,26 @@ services:
 image: docker:cli
 
 stages:
+    - checks
     - build
     - deploy
+
+variable checking:
+    stage: checks
+    script:
+        - |
+            check_variable() {
+              if [ -z "$1" ]; then
+             echo "Error: environment variable is not set."
+             exit 1
+              fi
+            }
+
+        - check_variable "$EC2_PEM_KEY"
+        - check_variable "$DOCKER_USERNAME"
+        - check_variable "$DOCKER_ACCESS_TOKEN"
+        - check_variable "$DOCKER_REPO"
+        - check_variable "$DOCKER_ENV_FILE"
 
 docker build:
     stage: build
@@ -28,6 +46,7 @@ deploy to EC2:
         - scp -i ec2.pem -o StrictHostKeyChecking=no ./docker-compose.yml admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com:~/
         - scp -i ec2.pem -o StrictHostKeyChecking=no ./$DOCKER_ENV_FILE admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com:~/
         - ssh -i ec2.pem -o StrictHostKeyChecking=no admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com "sudo docker compose --env-file "$DOCKER_ENV_FILE" down"
+        - ssh -i ec2.pem -o StrictHostKeyChecking=no admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com "sudo docker compose --env-file "$DOCKER_ENV_FILE" pull"
         - ssh -i ec2.pem -o StrictHostKeyChecking=no admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com "sudo docker compose --env-file "$DOCKER_ENV_FILE" up -d"
         - ssh -i ec2.pem -o StrictHostKeyChecking=no admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com "rm ~/docker-compose.yml"
         - ssh -i ec2.pem -o StrictHostKeyChecking=no admin@ec2-13-233-246-76.ap-south-1.compute.amazonaws.com "rm ~/"$DOCKER_ENV_FILE""
